import React from 'react';
import '../styles/globals.css';

export const metadata = {
  title: 'E-Commerce Store',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}